sylius_twig_hooks:
    hooks:
        'sylius_shop.account.order.show.content.main':
            credit_memos:
                component: 'sylius_refund:shop:account:credit_memos'
                props:
                    order: '@=_context.order'
                    template: '@SyliusRefundPlugin/shop/order/credit_memos.html.twig'
                priority: -100

        'sylius_shop.account.order.show.content.main.credit_memos':
            header:
                template: '@SyliusRefundPlugin/shop/order/credit_memos/header.html.twig'
                priority: 100
            list:
                template: '@SyliusRefundPlugin/shop/order/credit_memos/list.html.twig'
                priority: 0

        'sylius_shop.account.order.show.content.main.credit_memos.list':
            details:
                template: '@SyliusRefundPlugin/shop/order/credit_memos/list/details.html.twig'
                priority: 300
            total:
                template: '@SyliusRefundPlugin/shop/order/credit_memos/list/total.html.twig'
                priority: 100
            download:
                template: '@SyliusRefundPlugin/shop/order/credit_memos/list/download.html.twig'
                enabled: '%sylius_refund.pdf_generator.enabled%'
                priority: 0

        'sylius_shop.account.order.show.content.main.credit_memos.list.details':
            date:
                template: '@SyliusRefundPlugin/shop/order/credit_memos/list/details/date.html.twig'
                priority: 100
            number:
                template: '@SyliusRefundPlugin/shop/order/credit_memos/list/details/number.html.twig'
                priority: 0

