sylius_twig_hooks:
    hooks:
        'sylius_shop.account.order.show.content.main':
            credit_memos:
                component: 'sylius_refund:shop:account:credit_memos'
                props:
                    order: '@=_context.order'
                    template: '@SyliusRefundPlugin/shop/order/credit_memos.html.twig'
                priority: -100

        'sylius_shop.account.order.show.content.main.credit_memos':
            list_action_buttons:
                template: '@SyliusRefundPlugin/shop/order/download_button.html.twig'
                enabled: '%sylius_refund.pdf_generator.enabled%'
                priority: 0
