sylius_twig_hooks:
    hooks:
        'sylius_admin.order.show.content.header.title_block.actions':
            refunds:
                template: '@SyliusRefundPlugin/order/admin/content/header/title_block/actions/refunds.html.twig'
                priority: -100

        'sylius_admin.order.show.content.sections.payments':
            refund_header:
                template: '@SyliusRefundPlugin/order/admin/content/sections/payments/refund_header.html.twig'
                priority: -100
            refund_items:
                template: '@SyliusRefundPlugin/order/admin/content/sections/payments/refund_items.html.twig'
                priority: -200

        'sylius_admin.order.show.content.sections.payments.item.actions':
            refund:
                enabled: false

        'sylius_admin.order.show.content.sections.payments.refund_header':
            title:
                template: '@SyliusRefundPlugin/order/admin/content/sections/payments/header/title.html.twig'
                priority: 100

        'sylius_admin.order.show.content.sections.payments.refund_item':
            state:
                template: '@SyliusRefundPlugin/order/admin/content/sections/payments/item/state.html.twig'
                priority: 300
            name:
                template: '@SyliusRefundPlugin/order/admin/content/sections/payments/item/name.html.twig'
                priority: 200
            amount:
                template: '@SyliusRefundPlugin/order/admin/content/sections/payments/item/amount.html.twig'
                priority: 100
            actions:
                template: '@SyliusRefundPlugin/order/admin/content/sections/payments/item/actions.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections.payments.refund_item.actions':
            complete:
                template: '@SyliusRefundPlugin/order/admin/content/sections/payments/item/actions/complete.html.twig'
                priority: 100

        'sylius_admin.order.show.content.sections#left':
            credit_memos:
                template: '@SyliusRefundPlugin/order/admin/content/sections/credit_memos.html.twig'
                priority: 50

        'sylius_admin.order.show.content.sections.credit_memos':
            header:
                template: '@SyliusRefundPlugin/order/admin/content/sections/credit_memos/header.html.twig'
                priority: 100
            credit_memos:
                template: '@SyliusRefundPlugin/order/admin/content/sections/credit_memos/items.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections.credit_memos.header':
            title:
                template: '@SyliusRefundPlugin/order/admin/content/sections/credit_memos/header/title.html.twig'
                priority: 100

        'sylius_admin.order.show.content.sections.credit_memos.credit_memos.item.actions':
            download:
                template: '@SyliusRefundPlugin/order/admin/content/sections/credit_memos/item/actions/download.html.twig'
                enabled: '%sylius_refund.pdf_generator.enabled%'
                priority: 100
