imports:
    - { resource: "@SyliusRefundPlugin/config/twig_hooks/**/*.yaml" }
    - { resource: "@SyliusRefundPlugin/config/integrations.php" }

parameters:
    sylius_refund.credit_memo_save_path: "%kernel.project_dir%/private/credit_memos/"
    sylius_refund.filesystem_adapter.credit_memo: "sylius_refund_credit_memo"
    sylius_refund.refund_enum_type: Sylius\RefundPlugin\Entity\Type\RefundEnumType
    sylius_refund.refund_type: Sylius\RefundPlugin\Model\RefundType

sylius_refund:
    pdf_generator:
        allowed_files:
            - '%env(default:sylius_refund.default_logo_file:resolve:SYLIUS_REFUND_LOGO_FILE)%'

sylius_mailer:
    emails:
        units_refunded:
            subject: Units refunded
            template: "@SyliusRefundPlugin/email/units_refunded.html.twig"

framework:
    messenger:
        buses:
            sylius.command_bus: &command_bus
                middleware:
                    - 'validation'
                    - 'doctrine_transaction'
            sylius.event_bus: &event_bus
                default_middleware: allow_no_handlers
            sylius_refund_plugin.command_bus: *command_bus
            sylius_refund_plugin.event_bus: *event_bus
    workflows:
        sylius_refund_refund_payment:
            type: state_machine
            marking_store:
                type: method
                property: state
            supports:
                - Sylius\RefundPlugin\Entity\RefundPayment
            initial_marking: new
            places:
                - !php/const Sylius\RefundPlugin\Entity\RefundPaymentInterface::STATE_NEW
                - !php/const Sylius\RefundPlugin\Entity\RefundPaymentInterface::STATE_COMPLETED
            transitions:
                complete:
                    from: !php/const Sylius\RefundPlugin\Entity\RefundPaymentInterface::STATE_NEW
                    to: !php/const Sylius\RefundPlugin\Entity\RefundPaymentInterface::STATE_COMPLETED

sylius_grid:
    grids:
        sylius_refund_credit_memo:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius_refund.model.credit_memo.class%"
            sorting:
                number: asc
            fields:
                number:
                    type: string
                    label: sylius.ui.number
                    sortable: ~
                order:
                    type: twig
                    label: sylius.ui.order
                    sortable: order.number
                    options:
                        template: "@SyliusRefundPlugin/admin/order/grid/field/number.html.twig"
                channel:
                    type: twig
                    label: sylius.ui.channel
                    options:
                        template: "@SyliusRefundPlugin/admin/order/grid/field/channel.html.twig"
                total:
                    type: twig
                    label: sylius.ui.total
                    path: .
                    sortable: total
                    options:
                        template: "@SyliusAdmin/order/grid/field/order_total.html.twig"
                issuedAt:
                    type: datetime
                    label: sylius_refund.ui.issued_at
                    options:
                        format: 'Y-m-d H:i:s'
            actions:
                item:
                    show:
                        type: show
                        label: sylius.ui.show
                        icon: "tabler:eye"
                        options:
                            link:
                                route: sylius_refund_credit_memo_details
                                parameters:
                                    id: resource.id
                                    orderNumber: resource.order.number
                    download:
                        type: default
                        label: sylius_refund.ui.download
                        enabled: '%sylius_refund.pdf_generator.enabled%'
                        icon: "tabler:download"
                        options:
                            link:
                                route: sylius_refund_admin_credit_memo_download
                                parameters:
                                    id: resource.id
                    resend:
                        type: default
                        label: sylius_refund.ui.resend
                        icon: "tabler:send"
                        options:
                            link:
                                route: sylius_refund_admin_credit_memo_send
                                parameters:
                                    id: resource.id
            filters:
                number:
                    type: string
                    label: sylius.ui.number
                issuedAt:
                    type: date
                    label: sylius_refund.ui.issued_at
                channel:
                    type: entity
                    label: sylius.ui.channel
                    form_options:
                        class: "%sylius.model.channel.class%"

doctrine:
    dbal:
        types:
            sylius_refund_refund_type: "%sylius_refund.refund_enum_type%"

knp_gaufrette:
    adapters:
        sylius_refund_credit_memo:
            local:
                directory: "%sylius_refund.credit_memo_save_path%"
                create: true
    filesystems:
        sylius_refund_credit_memo:
            adapter: "%sylius_refund.filesystem_adapter.credit_memo%"
