sylius_twig_hooks:
    hooks:
        'sylius_refund.admin.credit_memos':
            sidebar:
                template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@SyliusAdmin/shared/crud/common/content.html.twig'
                priority: 0

        'sylius_refund.admin.credit_memos.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
                priority: 200
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 100
            sections:
                template: '@SyliusRefundPlugin/credit_memos/content/sections.html.twig'
                priority: 0

        'sylius_refund.admin.credit_memos.content.header':
            breadcrumbs:
                template: '@SyliusRefundPlugin/credit_memos/content/header/breadcrumbs.html.twig'
                priority: 100
            title_block:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block.html.twig'
                priority: 0

        'sylius_refund.admin.credit_memos.content.header.title_block':
            title:
                template: '@SyliusRefundPlugin/credit_memos/content/header/title_block/title.html.twig'
                priority: 100
            actions:
                template: '@SyliusRefundPlugin/credit_memos/content/header/title_block/actions.html.twig'
                priority: 0

        'sylius_refund.admin.credit_memos.content.header.title_block.actions':
            download:
                template: '@SyliusRefundPlugin/credit_memos/content/header/title_block/actions/download.html.twig'
                enabled: '%sylius_refund.pdf_generator.enabled%'
                priority: 100

        'sylius_refund.admin.credit_memos.content.sections':
            buyer:
                template: '@SyliusRefundPlugin/credit_memos/content/sections/buyer.html.twig'
                priority: 200
            seller:
                template: '@SyliusRefundPlugin/credit_memos/content/sections/seller.html.twig'
                priority: 100
            table:
                template: '@SyliusRefundPlugin/credit_memos/content/sections/table.html.twig'
                priority: 0
